insert into NECESSIDADE(DESCRICAO,ATIVA) values ('Deficiência visual',1)
insert into NECESSIDADE(DESCRICAO,ATIVA) values ('Deficiência auditiva',1)
insert into NECESSIDADE(DESCRICAO,ATIVA) values ('Deficiência mental',1)
insert into NECESSIDADE(DESCRICAO,ATIVA) values ('Deficiência Física',1)
insert into NECESSIDADE(DESCRICAO,ATIVA) values ('Deficiência Múltipla',1)

INSERT INTO PARAMETROS(PARAMETRO,VALOR,SITUACAO) VALUES('VersaoSistema','1.0.0.0',1)
INSERT INTO PARAMETROS(PARAMETRO,VALOR,SITUACAO) VALUES('URLAtualizacao','https://doc-08-0s-docs.googleusercontent.com/docs/securesc/q8c8t00hu757nukr1dhokhr7te6jc9ik/an0dnkmhk7065nca7q03i15qd6r1mtqh/1528192800000/09646512410485598135/09646512410485598135/1l_OavrMvxZUmJH6xmw5Phgr3umbkfrMB?e=download&nonce=qv8o3gg1qp810&user=09646512410485598135&hash=75gfqbtn55ov96dmc5f4tb4u4ecdh8c0',1)
INSERT INTO PARAMETROS(PARAMETRO,VALOR,SITUACAO) VALUES('QtdVagas','20',1)

insert into GENERO(DESCRICAO) VALUES('Masculino')
insert into GENERO(DESCRICAO) VALUES('Feminino')

INSERT INTO GRUPOACESSO(NOME) VALUES('ADMIN')
INSERT INTO PERMISSOES(TIPO,NOME,COMPONENTE,SITUACAO) VALUES(0,'Cad. Alunos','frmCadastroAlunos',1)
INSERT INTO PERMISSOES(TIPO,NOME,COMPONENTE,SITUACAO) VALUES(0,'Cad. Candidatos','frmCadastroCandidatos',1)
insert into GRUPOACESSO_PERMISSOES(GRUPOACESSO,PERMISSOES) select  (select  max(GRUPOACESSO) from GRUPOACESSO ),PERMISSOES  from PERMISSOES


INSERT INTO PROFISSAO(DESCRICAO) VALUES('PSICÓLOGO'),('PROFESSOR'),('GERENTE'),('COORDENADOR'),('RECEPCIONISTA')
INSERT INTO TIPO(VALOR,DESCRICAO,TABELA_ORIGEM) VALUES (1,'TEL','CONTATO'),(2,'CEL','CONTATO')
INSERT INTO TIPO(VALOR,DESCRICAO,TABELA_ORIGEM) VALUES (0,'TELA','PERMISSOES'),(1,'INCLUIR','PERMISSOES'),(2,'ALTERAR','PERMISSOES'),(3,'EXCLUIR','PERMISSOES'),(4,'CONSULTAR','PERMISSOES')

INSERT INTO TIPO(VALOR,DESCRICAO,TABELA_ORIGEM) VALUES (1,'RUA','ENDERECO'),(2,'AVENIDA','ENDERECO'),(3,'ALAMEDA','ENDERECO')


