--UPDATE PARAMETROS SET VALOR = 'FTP://MABLESAAF-COM.UMBLER.NET/EXE/SAAF.EXE' WHERE PARAMETRO = 'URLATUALIZACAO'
--UPDATE PARAMETROS SET VALOR = '1.0.0.1' WHERE PARAMETRO = 'VERSAOSISTEMA'
/*
SELECT 
		PARAMETROS
		,PARAMETRO
		,VALOR
		,SITUACAO
FROM PARAMETROS

UNION ALL

SELECT 
 99999999 AS PARAMETROS 
,'QTDALUNOSATIVOS' AS PARAMETRO 
, CAST( COUNT(*) AS VARCHAR(10)) AS VALOR 
, 1 AS SITUACAO
FROM ALUNO WHERE SITUACAO = 1
*/




--DROP TABLE LOCALIDADE; CUIDADO!
--DROP TABLE UF; CUIDADO!
/*

DROP TABLE ACOMPANHAMENTO;  
DROP TABLE USUARIO;  
DROP TABLE GRUPOACESSO_PERMISSOES;
DROP TABLE PERMISSOES;  
DROP TABLE GRUPOACESSO;  
DROP TABLE CONTRATO;  
DROP TABLE EMPRESA;  
DROP TABLE FUNCIONARIO;  
DROP TABLE PROFISSAO;  
DROP TABLE DOCUMENTO;  
DROP TABLE ALUNO;  
DROP TABLE CANDIDATO_NECESSIDADE;  
DROP TABLE NECESSIDADE;  
DROP TABLE PRONTUARIO;  
DROP TABLE CANDIDATO;  
DROP TABLE GENERO;  
DROP TABLE CONTATO;  
DROP TABLE ENDERECOPESSOA;  
DROP TABLE ENDERECO;  
DROP TABLE PESSOA;  
DROP TABLE TIPO;  
DROP TABLE PARAMETROS;  
DROP TABLE LOCALIDADE;  
DROP TABLE UF;  

*/
/*SELECT    OBJECT_NAME(CONSTID) FK, OBJECT_NAME(FKEYID) TABELA_FILHA, OBJECT_NAME(RKEYID) TABELA_PAI, COL_NAME(RKEYID, RKEY) COLUNAS_PAI, COL_NAME(FKEYID, FKEY) COLUNAS_PAI
FROM    SYSFOREIGNKEYS */


/* ***********FEITO NA CARGA*****************/
CREATE TABLE UF(
 UF INT AUTO_INCREMENT
,NOME_UF VARCHAR(50)
,SIGLA VARCHAR(15)
,PRIMARY KEY (UF)
);

CREATE TABLE LOCALIDADE(
 LOCALIDADE INT AUTO_INCREMENT
,UF INT
,NOME_LOCALIDADE VARCHAR(100)
,PRIMARY KEY (LOCALIDADE)
);


CREATE TABLE PARAMETROS(
 PARAMETROS INT AUTO_INCREMENT
,PARAMETRO VARCHAR(255)
,VALOR VARCHAR(1000)
,SITUACAO INT
,PRIMARY KEY (PARAMETROS)
);


CREATE TABLE TIPO(
 TIPO INT AUTO_INCREMENT
,VALOR INT
,DESCRICAO VARCHAR(255)
,TABELA_ORIGEM VARCHAR(255)
,PRIMARY KEY (TIPO)
);


CREATE TABLE PESSOA(
 PESSOA INT AUTO_INCREMENT
,CPF_CNPJ VARCHAR(15)
,RG VARCHAR(150)
,EMAIL VARCHAR(255)
,PRIMARY KEY (PESSOA)
);




CREATE TABLE ENDERECO(
 ENDERECO INT AUTO_INCREMENT
,TIPO VARCHAR(15)
,LOCATARIO VARCHAR(255)
,LOCALIDADE INT
,UF INT
,CEP VARCHAR(11)
,BAIRRO  VARCHAR(100)
,NUMERO VARCHAR(20)
,PRIMARY KEY (ENDERECO)
,FOREIGN KEY (UF) REFERENCES UF(UF)
,FOREIGN KEY (LOCALIDADE) REFERENCES LOCALIDADE(LOCALIDADE)
);
 

 

 
CREATE TABLE ENDERECOPESSOA(
 ENDERECOPESSOA INT AUTO_INCREMENT
,ENDERECO INT
,PESSOA INT
,PRIMARY KEY (ENDERECOPESSOA)
,FOREIGN KEY (PESSOA) REFERENCES PESSOA(PESSOA)
,FOREIGN KEY (ENDERECO) REFERENCES ENDERECO(ENDERECO)
);


 

 
CREATE TABLE CONTATO(
 CONTATO INT AUTO_INCREMENT
,PESSOA INT 
,TIPO INT
,VALOR VARCHAR(255)
,PRIMARY KEY (CONTATO)
,FOREIGN KEY (PESSOA) REFERENCES PESSOA(PESSOA)
);

CREATE TABLE GENERO(
 GENERO INT AUTO_INCREMENT 
,DESCRICAO VARCHAR(50)
,PRIMARY KEY (GENERO)
);


CREATE TABLE CANDIDATO(
 CANDIDATO INT AUTO_INCREMENT
,PESSOA INT
,NOME VARCHAR(255)
,DATA_CADASTRO DATETIME
,DATA_NASCIMENTO DATE
,NOME_PAI VARCHAR(255)
,NOME_MAE VARCHAR(255)
,ETINIA INT
,GENERO INT
,RESPONSAVEL VARCHAR(255)
,PARENTESCO VARCHAR(100)
,ENCAMINHADO VARCHAR(100)
,PROCEDENCIA VARCHAR(100)
,FOTO BLOB 
,PRONTUARIO TEXT
,NIS VARCHAR(20)
,PAI_NASCIMENTO			DATETIME	
,MAE_NASCIMENTO			DATETIME
,RESPONSAVEL_NASCIMENTO	 DATETIME
,PROFISSAO					VARCHAR(50)
,ESCOLARIDADE				VARCHAR(50)
,PRIMARY KEY (CANDIDATO)
,FOREIGN KEY (PESSOA) REFERENCES PESSOA(PESSOA)
,FOREIGN KEY (GENERO) REFERENCES GENERO(GENERO)

);


CREATE TABLE PRONTUARIO(
 PRONTUARIO INT AUTO_INCREMENT
,CANDIDATO INT
,FAZUSODEMEDICAMENTOS INT
,FAZUSODEMEDICAMENTOS_QUAL VARCHAR(255)
,ALERGICOALGUMMEDICAMENTO  INT
,ALERGICOALGUMMEDICAMENTO_QUAL VARCHAR(255)
,POSSUIBILHETEESPECIALTRANSPORTE INT
,POSSUIBILHETEESPECIALTRANSPORTE_QUAL VARCHAR(255)
,RECEBEPROGRAMATRANSFERENCIARENDA INT
,RECEBEPROGRAMATRANSFERENCIARENDA_QUAL VARCHAR(255)
,AUTORIZADOIREMBORASOZINHO  INT
,AUTORIZADOSERFILMADOFOTOGRAFADO INT
,AUTORIZADOPARTICIPARATIVIDADESEXTERNAS INT
,COMPARECERDIARIAMENTE  INT
,PERIODOADAPTACO VARCHAR(255)
,DIASINDICADOSFREQUENCIA VARCHAR(255)
,PODERAALMOCARORGANIZACO INT
,PODERAALMOCARORGANIZACO_MOTIVO VARCHAR(255)
,ALERGICORESTRICOALGUMALIMENTO INT
,ALERGICORESTRICOALGUMALIMENTO_QUAL VARCHAR(255)

,DATA_REF DATETIME
,PRIMARY KEY (PRONTUARIO)
,FOREIGN KEY (CANDIDATO) REFERENCES CANDIDATO(CANDIDATO)
);




CREATE TABLE NECESSIDADE(
 NECESSIDADE INT AUTO_INCREMENT
,ATIVA INT
,DESCRICAO VARCHAR(255)
,PRIMARY KEY (NECESSIDADE)
);




CREATE TABLE CANDIDATO_NECESSIDADE(
 CANDIDATO_NECESSIDADE INT AUTO_INCREMENT
,NECESSIDADE INT 
,CANDIDATO INT
,PRIMARY KEY (CANDIDATO_NECESSIDADE)
,FOREIGN KEY (CANDIDATO) REFERENCES CANDIDATO(CANDIDATO)
,FOREIGN KEY (NECESSIDADE) REFERENCES NECESSIDADE(NECESSIDADE)
);



CREATE TABLE ALUNO(
 ALUNO INT AUTO_INCREMENT
,CANDIDATO INT
,MATRICULA INT
,DATA_MATRICULA DATETIME
,SITUACAO INT
,PRIMARY KEY (ALUNO)
,FOREIGN KEY (CANDIDATO) REFERENCES CANDIDATO(CANDIDATO)
);




CREATE TABLE DOCUMENTO(
 DOCUMENTO INT AUTO_INCREMENT
,ANEXO TEXT
,DATAANEXO DATETIME
,ALUNO INT
,PRIMARY KEY (DOCUMENTO)
,FOREIGN KEY (ALUNO) REFERENCES ALUNO(ALUNO)
);



CREATE TABLE PROFISSAO(
 PROFISSAO INT AUTO_INCREMENT
,DESCRICAO VARCHAR(255)
,PRIMARY KEY (PROFISSAO)
);


CREATE TABLE FUNCIONARIO(
 FUNCIONARIO INT AUTO_INCREMENT
,PESSOA INT
,ADMISSAO DATETIME
,DEMISSAO DATETIME
,PROFISSAO INT
,NOME VARCHAR(255)
,DTNASCIMENTO DATETIME
,PRIMARY KEY (FUNCIONARIO)
,FOREIGN KEY (PROFISSAO) REFERENCES PROFISSAO(PROFISSAO)
,FOREIGN KEY (PESSOA) REFERENCES PESSOA(PESSOA)
);






CREATE TABLE EMPRESA(
 EMPRESA INT AUTO_INCREMENT
,PESSOA INT
,RAZAO VARCHAR(255)
,FANTASIA VARCHAR(255)
,PRIMARY KEY (EMPRESA)
,FOREIGN KEY (PESSOA) REFERENCES PESSOA(PESSOA)
);




CREATE TABLE CONTRATO(
 CONTRATO INT AUTO_INCREMENT
,ALUNO INT
,EMPRESA INT
,DATA_ADMISSAO DATETIME
,OBSERVACOES TEXT
,PRIMARY KEY (CONTRATO)
,FOREIGN KEY (ALUNO) REFERENCES ALUNO(ALUNO)
,FOREIGN KEY (EMPRESA) REFERENCES EMPRESA(EMPRESA)
);




CREATE TABLE GRUPOACESSO(
 GRUPOACESSO INT AUTO_INCREMENT
,NOME VARCHAR(100)
,PRIMARY KEY (GRUPOACESSO)
);



CREATE TABLE PERMISSOES(
 PERMISSOES INT AUTO_INCREMENT
,TIPO INT  -- 0 = TELA / 1 = BOTAO / 2 = ????
,NOME VARCHAR(255)  -- EX. CADASTRO DE ALUNO
,COMPONENTE VARCHAR(255) -- UCADALUNO 
,SITUACAO INT  -- ATIVO OU INATIVA RECURSO
,PRIMARY KEY (PERMISSOES)
);




CREATE TABLE GRUPOACESSO_PERMISSOES(
 GRUPOACESSO_PERMISSOES INT AUTO_INCREMENT
,GRUPOACESSO INT
,PERMISSOES INT
,PRIMARY KEY (GRUPOACESSO_PERMISSOES)
,FOREIGN KEY (GRUPOACESSO) REFERENCES GRUPOACESSO(GRUPOACESSO)
,FOREIGN KEY (PERMISSOES) REFERENCES PERMISSOES(PERMISSOES)
);


CREATE TABLE USUARIO(
 USUARIO INT AUTO_INCREMENT
,USR_LOGIN VARCHAR(100)
,USR_SENHA VARCHAR(100)
,PESSOA INT
,GRUPOACESSO INT
,FUNCIONARIO INT
,SITUACAO INT
,PRIMARY KEY (USUARIO)
,FOREIGN KEY (GRUPOACESSO) REFERENCES GRUPOACESSO(GRUPOACESSO)
,FOREIGN KEY (FUNCIONARIO) REFERENCES FUNCIONARIO(FUNCIONARIO)
);



CREATE TABLE ACOMPANHAMENTO(
 ACOMPANHAMENTO INT AUTO_INCREMENT
,ALUNO INT
,FUNCIONARIO INT
,DATA DATETIME
,DATARETORNO DATETIME
,OBSERVACOES VARCHAR(500)
,PRIMARY KEY (ACOMPANHAMENTO)
,FOREIGN KEY (ALUNO) REFERENCES ALUNO(ALUNO)
,FOREIGN KEY (FUNCIONARIO) REFERENCES FUNCIONARIO(FUNCIONARIO)
);




/* CARGA!

INSERT INTO NECESSIDADE(DESCRICAO,ATIVA) VALUES ('DEFICIÊNCIA VISUAL',1)
INSERT INTO NECESSIDADE(DESCRICAO,ATIVA) VALUES ('DEFICIÊNCIA AUDITIVA',1)
INSERT INTO NECESSIDADE(DESCRICAO,ATIVA) VALUES ('DEFICIÊNCIA MENTAL',1)
INSERT INTO NECESSIDADE(DESCRICAO,ATIVA) VALUES ('DEFICIÊNCIA FÍSICA',1)
INSERT INTO NECESSIDADE(DESCRICAO,ATIVA) VALUES ('DEFICIÊNCIA MÚLTIPLA',1)

INSERT INTO PARAMETROS(PARAMETRO,VALOR,SITUACAO) VALUES('VERSAOSISTEMA','1.0.0.0',1)
INSERT INTO PARAMETROS(PARAMETRO,VALOR,SITUACAO) VALUES('URLATUALIZACAO','HTTPS://DOC-08-0S-DOCS.GOOGLEUSERCONTENT.COM/DOCS/SECURESC/Q8C8T00HU757NUKR1DHOKHR7TE6JC9IK/AN0DNKMHK7065NCA7Q03I15QD6R1MTQH/1528192800000/09646512410485598135/09646512410485598135/1L_OAVRMVXZUMJH6XMW5PHGR3UMBKFRMB?E=DOWNLOAD&NONCE=QV8O3GG1QP810&USER=09646512410485598135&HASH=75GFQBTN55OV96DMC5F4TB4U4ECDH8C0',1)
INSERT INTO PARAMETROS(PARAMETRO,VALOR,SITUACAO) VALUES('QTDVAGAS','20',1)
INSERT INTO  PARAMETROS(PARAMETRO,VALOR,SITUACAO) VALUES ('TAMANHO_EXE','45298688',1)



INSERT INTO GENERO(DESCRICAO) VALUES('MASCULINO')
INSERT INTO GENERO(DESCRICAO) VALUES('FEMININO')

INSERT INTO GRUPOACESSO(NOME) VALUES('ADMIN')
INSERT INTO PERMISSOES(TIPO,NOME,COMPONENTE,SITUACAO) VALUES(0,'CAD. ALUNOS','FRMCADASTROALUNOS',1)
INSERT INTO PERMISSOES(TIPO,NOME,COMPONENTE,SITUACAO) VALUES(0,'CAD. CANDIDATOS','FRMCADASTROCANDIDATOS',1)
INSERT INTO GRUPOACESSO_PERMISSOES(GRUPOACESSO,PERMISSOES) SELECT  (SELECT  MAX(GRUPOACESSO) FROM GRUPOACESSO ),PERMISSOES  FROM PERMISSOES


INSERT INTO PROFISSAO(DESCRICAO) VALUES('PSICÓLOGO'),('PROFESSOR'),('GERENTE'),('COORDENADOR'),('RECEPCIONISTA')
INSERT INTO TIPO(VALOR,DESCRICAO,TABELA_ORIGEM) VALUES (1,'TEL','CONTATO'),(2,'CEL','CONTATO')
INSERT INTO TIPO(VALOR,DESCRICAO,TABELA_ORIGEM) VALUES (0,'TELA','PERMISSOES'),(1,'INCLUIR','PERMISSOES'),(2,'ALTERAR','PERMISSOES'),(3,'EXCLUIR','PERMISSOES'),(4,'CONSULTAR','PERMISSOES')

INSERT INTO TIPO(VALOR,DESCRICAO,TABELA_ORIGEM) VALUES (1,'RUA','ENDERECO'),(2,'AVENIDA','ENDERECO'),(3,'ALAMEDA','ENDERECO')



*/
/*
SELECT * FROM PESSOA;
SELECT * FROM ALUNO;
SELECT * FROM CANDIDATO;
SELECT * FROM EMPRESA;
SELECT * FROM TIPO;
SELECT * FROM CONTRATO

SELECT * FROM CONTATO;
SELECT * FROM NECESSIDADE;
SELECT * FROM PROFISSAO;
SELECT * FROM FUNCIONARIO;
SELECT * FROM ACOMPANHAMENTO
*/
/*

SELECT TIPO,DESCRICAO FROM TIPO WHERE TABELA_ORIGEM = 'ENDERECO'
INSERT INTO TIPO(DESCRICAO,TABELA_ORIGEM) VALUES 
 ('RUA','ENDERECO')
,('AVENIDA','ENDERECO')
*/


/**
UPDATE LOCALIDADE  SET NOME_LOCALIDADE = REPLACE(NOME_LOCALIDADE,'Ã','A') 
UPDATE LOCALIDADE  SET NOME_LOCALIDADE = REPLACE(NOME_LOCALIDADE,'Ã','A') 
UPDATE LOCALIDADE  SET NOME_LOCALIDADE = REPLACE(NOME_LOCALIDADE,'Á','A')
UPDATE LOCALIDADE  SET NOME_LOCALIDADE = REPLACE(NOME_LOCALIDADE,'À','A')
UPDATE LOCALIDADE  SET NOME_LOCALIDADE = REPLACE(NOME_LOCALIDADE,'Ã','A')
UPDATE LOCALIDADE  SET NOME_LOCALIDADE = REPLACE(NOME_LOCALIDADE,'Â','A')
UPDATE LOCALIDADE  SET NOME_LOCALIDADE = REPLACE(NOME_LOCALIDADE,'Ä','A')
UPDATE LOCALIDADE  SET NOME_LOCALIDADE = REPLACE(NOME_LOCALIDADE,'Á','A')
UPDATE LOCALIDADE  SET NOME_LOCALIDADE = REPLACE(NOME_LOCALIDADE,'À','A')
UPDATE LOCALIDADE  SET NOME_LOCALIDADE = REPLACE(NOME_LOCALIDADE,'Ã','A')
UPDATE LOCALIDADE  SET NOME_LOCALIDADE = REPLACE(NOME_LOCALIDADE,'Â','A')
UPDATE LOCALIDADE  SET NOME_LOCALIDADE = REPLACE(NOME_LOCALIDADE,'Ä','A')
UPDATE LOCALIDADE  SET NOME_LOCALIDADE = REPLACE(NOME_LOCALIDADE,'É','E')
UPDATE LOCALIDADE  SET NOME_LOCALIDADE = REPLACE(NOME_LOCALIDADE,'È','E')
UPDATE LOCALIDADE  SET NOME_LOCALIDADE = REPLACE(NOME_LOCALIDADE,'É','E')
UPDATE LOCALIDADE  SET NOME_LOCALIDADE = REPLACE(NOME_LOCALIDADE,'È','E')
UPDATE LOCALIDADE  SET NOME_LOCALIDADE = REPLACE(NOME_LOCALIDADE,'Í','I')
UPDATE LOCALIDADE  SET NOME_LOCALIDADE = REPLACE(NOME_LOCALIDADE,'Ì','I')
UPDATE LOCALIDADE  SET NOME_LOCALIDADE = REPLACE(NOME_LOCALIDADE,'Í','I')
UPDATE LOCALIDADE  SET NOME_LOCALIDADE = REPLACE(NOME_LOCALIDADE,'Ì','I')
UPDATE LOCALIDADE  SET NOME_LOCALIDADE = REPLACE(NOME_LOCALIDADE,'Ó','O')
UPDATE LOCALIDADE  SET NOME_LOCALIDADE = REPLACE(NOME_LOCALIDADE,'Ò','O')
UPDATE LOCALIDADE  SET NOME_LOCALIDADE = REPLACE(NOME_LOCALIDADE,'Ö','O')
UPDATE LOCALIDADE  SET NOME_LOCALIDADE = REPLACE(NOME_LOCALIDADE,'Õ','O')
UPDATE LOCALIDADE  SET NOME_LOCALIDADE = REPLACE(NOME_LOCALIDADE,'Ô','O')
UPDATE LOCALIDADE  SET NOME_LOCALIDADE = REPLACE(NOME_LOCALIDADE,'Ó','O')
UPDATE LOCALIDADE  SET NOME_LOCALIDADE = REPLACE(NOME_LOCALIDADE,'Ò','O')
UPDATE LOCALIDADE  SET NOME_LOCALIDADE = REPLACE(NOME_LOCALIDADE,'Ö','O')
UPDATE LOCALIDADE  SET NOME_LOCALIDADE = REPLACE(NOME_LOCALIDADE,'Õ','O')
UPDATE LOCALIDADE  SET NOME_LOCALIDADE = REPLACE(NOME_LOCALIDADE,'Ô','O')
UPDATE LOCALIDADE  SET NOME_LOCALIDADE = REPLACE(NOME_LOCALIDADE,'Ú','U')
UPDATE LOCALIDADE  SET NOME_LOCALIDADE = REPLACE(NOME_LOCALIDADE,'Ù','U')
UPDATE LOCALIDADE  SET NOME_LOCALIDADE = REPLACE(NOME_LOCALIDADE,'Ü','U')
UPDATE LOCALIDADE  SET NOME_LOCALIDADE = REPLACE(NOME_LOCALIDADE,'Ú','U')
UPDATE LOCALIDADE  SET NOME_LOCALIDADE = REPLACE(NOME_LOCALIDADE,'Ù','U')
UPDATE LOCALIDADE  SET NOME_LOCALIDADE = REPLACE(NOME_LOCALIDADE,'Ü','U')
UPDATE LOCALIDADE  SET NOME_LOCALIDADE = REPLACE(NOME_LOCALIDADE,'Ç','C')
UPDATE LOCALIDADE  SET NOME_LOCALIDADE = REPLACE(NOME_LOCALIDADE,'Ç','C')
UPDATE LOCALIDADE  SET NOME_LOCALIDADE = REPLACE(NOME_LOCALIDADE,'Ñ','N')
UPDATE LOCALIDADE  SET NOME_LOCALIDADE = REPLACE(NOME_LOCALIDADE,'Ñ','N')
*/