--SELECT * FROM TIPO
/*
SELECT * FROM PESSOA
SELECT * FROM ALUNO
SELECT * FROM CANDIDATO
SELECT * FROM CONTATO
SELECT * FROM ENDERECO
SELECT * FROM ENDERECOPESSOA
*/
select * from ACOMPANHAMENTO

DECLARE @COMP VARCHAR(10);
SELECT @COMP = CAST(COUNT(1)+1 AS VARCHAR(10)) FROM PESSOA
INSERT INTO PESSOA(CPF_CNPJ,EMAIL,RG) VALUES ('99999999999','TESTE_'+@COMP+'@GMAIL.COM','99999999')

INSERT INTO CANDIDATO(PESSOA,NOME,DATA_CADASTRO,DATA_NASCIMENTO) VALUES( 
(SELECT MAX(PESSOA) FROM PESSOA)
,'ALUNO TESTE '+@COMP
,'2018-01-01'
,'2010-01-01'
)

INSERT INTO ENDERECO(TIPO,LOCATARIO,LOCALIDADE,UF,CEP,BAIRRO) VALUES(5,'ENDERECO TESTE_'+@COMP,1,1,'01111111','TESTE')


INSERT INTO ENDERECOPESSOA(ENDERECO,PESSOA) VALUES (
 (SELECT MAX(ENDERECO) FROM ENDERECO)
,(SELECT MAX(PESSOA) FROM PESSOA)
)


INSERT INTO CONTATO(PESSOA,TIPO,VALOR) VALUES((SELECT MAX(PESSOA) FROM PESSOA),7,'988888888')


